version: '3'
services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        # 環境變量
        environment:
            # mysql密碼
            - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_PASSWORD
        container_name: "mysql"
    
    php:
        build: ./php-mysqli
        # image指定build Dockerfile生成鏡像的名稱
        image: php:7.2-fpm-mysqli
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/html:/var/www/html"
        links :
            - mysql
        container_name: "php7"

    nginx:
        image: nginx:latest
        # 端口映射
        ports:
            - "80:80"
        # 相依關係，先跑php
        depends_on:
            - "php"
        # 數據卷
        volumes:
            # 映射本機的./conf.d目錄到Docker容器中的/etc/nginx/conf.d目錄
            - "$PWD/conf.d:/etc/nginx/conf.d"
            - "$PWD/html:/usr/share/nginx/html"
        links :
            - php
        # 容器名稱
        container_name: "nginx"
